[src.tuba]
type = "bsv"
src-files = [
    "../gfe/bluespec-processors/P3/Tuba/src_Core/*/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/coherence/src/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/connectal/bsv/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/connectal/lib/bsv/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/connectal/tests/spi/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/fpgautils/lib/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/procs/RV64G_OOO/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Core/RISCY_OOO/procs/lib/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Testbench/*/*.bsv",
    "../gfe/bluespec-processors/P3/Tuba/src_Testbench/*/*/*.bsv",
]
ast-dir = "examples/tuba/ast"

bsc-flags = [
    "-D", "NUM_CORES=1",
    "-D", "XILINX_FP_FMA_LATENCY=3",
    "-D", "XILINX_INT_MUL_LATENCY=2",
]

bsc-config-flags = [
    "-D", "RV64",
    "-D", "ISA_PRIV_M",
    "-D", "ISA_PRIV_U",
    "-D", "ISA_PRIV_S",
    "-D", "SV39",
    "-D", "ISA_I",
    "-D", "ISA_M",
    "-D", "ISA_A",
    "-D", "ISA_F",
    "-D", "ISA_D",
    "-D", "ISA_FD_DIV",
    "-D", "ISA_C",
    "-D", "SHIFT_BARREL",
    "-D", "MULT_SYNTH",
    "-D", "Near_Mem_Caches",
    "-D", "FABRIC64",
    "-D", "BSIM",
]

[design]
root-module = "Top_HW_Side.mkTop_HW_Side"


[graphviz]
draw-nets = false
draw-logics = false
draw-ext-ports = true
draw-logic-ports = true
dedup-edges = true
shorten-net-names = true


# Feature-model synthesis configuration
[featuresynth]
list-features-command = "./driver %c list-pp-flags"
oracle-command = "examples/tuba/check-config.sh %c %i"
#oracle-cache-file = "examples/tuba/oracle.cache"
init-tests-file = "examples/tuba/init-tests.rktd"
#resume-tests-file = "examples/tuba/resume-tests.rktd"
max-groups = 3
max-dependencies = 3
out-file = "piccolo.fm.json"
reason-threshold = 5

hard-constraints = [
    "(! BOARD_xsim)",
    "BSIM",
    "(! BSV_POSITIVE_RESET)",
    "CACHE_LARGE",
    "(! CACHE_MC_1MB)",
    "(! CACHE_MC_2MB)",
    "(! CACHE_SMALL)",
    "(! CHECK_DEADLOCK)",
    "(! CORE_BOOM)",
    "(! CORE_LARGE)",
    "(! CORE_LARGE_WIDE)",
    "(! CORE_MEDIUM)",
    "CORE_SMALL",
    "(! CORE_SMALL_WIDE)",
    "(! CORE_TINY)",
    "(! DEBUG_DMA)",
    "(! DEBUG_ICACHE)",
    "(! DIR_PRED_BHT)",
    "(! DIR_PRED_GSELECT)",
    "(! DIR_PRED_GSHARE)",
    "(! DISABLE_SECURE_BW)",
    "(! DISABLE_SECURE_FLUSH_BP)",
    "(! DISABLE_SECURE_FLUSH_CACHE)",
    "(! DISABLE_SECURE_FLUSH_TLB)",
    "(! DISABLE_SECURE_LLC)",
    "(! DISABLE_SECURE_LLC_ARBITER)",
    "(! DISABLE_SECURE_LLC_MSHR)",
    "(! EXTERNAL_DEBUG_MODULE)",
    "(! FABRIC32)",
    "FABRIC64",
    "(! HTIF_MEMORY)",
    "(! INCLUDE_ACCEL0)",
    "(! INCLUDE_CAMERA_MODEL)",
    "(! INCLUDE_GDB_CONTROL)",
    "(! INCLUDE_INITIAL_MEMZERO)",
    "(! INCLUDE_TANDEM_VERIF)",
    "(! INORDER_CORE)",
    "ISA_D",
    "ISA_F",
    "ISA_FD_DIV",
    "(! ISA_F_OR_D)",
    "ISA_PRIV_S",
    "(! IVERILOG)",
    "(! LR_UP_TO_E)",
    "(! NO_LOAD_RESP_E)",
    "(! Near_Mem_TCM)",
    "(! PERF_COUNT)",
    "(! PcieClockPeriod)",
    "(! RENAME_DEBUG)",
    "(! RV128)",
    "(! RV32)",
    "RV64",
    "(! SECURITY)",
    "(! SELF_INV_CACHE)",
    #"(! SIMULATION)",
    "(! SIM_LLC_ARBITER_NUM)",
    "(! SIM_LOG_LLC_PARTITION_NUM)",
    "(! SV34)",
    "SV39",
    "(! SYSTEM_SELF_INV_L1D)",
    "(! TSO_MM)",
    "USE_BSV_BRAM_SYNC_FIFO",
    "(! USE_CONNECTAL_BRAM_SYNC_FIFO)",
    "USE_XILINX_FPU",
    "(! USE_XILINX_SYNC_FIFO)",
    "(! XILINX)",
    "(! XilinxUltrascale)",
]

