[src.boom]
type = "chisel"
source-file = "../gfe/chisel_processors/chipyard/sims/verilator/generated-src/example.TestHarnessGFE.BoomP3FPGAConfig/example.TestHarnessGFE.BoomP3FPGAConfig.top.fir"
ast-file = "gfe-configs/boom/ast.cbor"

blackbox-modules = [ "TLDebugModuleInner" ]


[graphviz]
draw-nets = false
draw-logics = false
draw-ext-ports = true
draw-logic-ports = true
dedup-edges = true
shorten-net-names = true


# Feature-model synthesis configuration
[featuresynth]
list-features-command = "boom/list-features.sh"
oracle-command = "boom/check-config.sh"
init-tests-file = "boom/init-tests.rktd"
max-groups = 3
max-dependencies = 3
out-file = "boom.fm.json"
reason-threshold = 10
boredom-threshold = 2000

hard-constraints = [
    "(! boom.common.WithBoomRV32)",
    "(! freechips.rocketchip.subsystem.WithRV32)",
    "(! freechips.rocketchip.subsystem.With1TinyCore)",
    "(! boom.common.WithSmallBooms)",
    "(! boom.common.WithMediumBooms)",
    "(! boom.common.WithMegaBooms)",

    # Previous synthesis runs reported that these features can't be enabled or
    # have no effect.  We blacklist them in the config so that future synthesis
    # runs don't have to re-discover this information.
    "(! boom.common.WithUnifiedMemIntIQs)",
    "(! freechips.rocketchip.subsystem.WithDefaultBtb)",
    "(! freechips.rocketchip.subsystem.WithFPUWithoutDivSqrt)",
    "(! freechips.rocketchip.subsystem.WithFastMulDiv)",
    "(! freechips.rocketchip.subsystem.WithNoMMIOPort)",
    "(! freechips.rocketchip.subsystem.WithNoMemPort)",
    "(! freechips.rocketchip.subsystem.WithNoSlavePort)",
    "(! freechips.rocketchip.subsystem.WithRoccExample)",
    "(! freechips.rocketchip.subsystem.WithScratchpadsOnly)",
    "(! freechips.rocketchip.subsystem.WithSynchronousRocketTiles)",
    "(! freechips.rocketchip.subsystem.WithoutFPU)",
    "(! freechips.rocketchip.subsystem.WithoutMulDiv)",
]
