[src.rocket]
type = "chisel"
source-file = "../gfe/chisel_processors/rocket-chip/vsim/generated-src/galois.system.P2TVFPGAConfig.fir"
ast-file = "gfe-configs/rocket-p2/ast.cbor"

blackbox-modules = [ "TLDebugModuleInner", "TVEncoder" ]


[graphviz]
draw-nets = false
draw-logics = false
draw-ext-ports = true
draw-logic-ports = true
dedup-edges = true
shorten-net-names = true


# Feature-model synthesis configuration
[featuresynth]
list-features-command = "rocket-p2/list-features.sh"
oracle-command = "rocket-p2/check-config.sh"
init-tests-file = "rocket-p2/init-tests.rktd"
max-groups = 4
max-dependencies = 6
out-file = "rocket-p2.fm.json"
reason-threshold = 10
boredom-threshold = 2000

hard-constraints = [
    "(! galois.subsystem.WithRV32)",
    "(! galois.subsystem.With1TinyCore)",

    # Previous synthesis runs reported that these features can't be enabled or
    # have no effect.  We blacklist them in the config so that future synthesis
    # runs don't have to re-discover this information.
    "(! galois.subsystem.WithDefaultBtb)",
    "(! galois.subsystem.WithFastMulDiv)",
    "(! galois.subsystem.WithNoMMIOPort)",
    "(! galois.subsystem.WithNoMemPort)",
    "(! galois.subsystem.WithNoSlavePort)",
    "(! galois.subsystem.WithScratchpadsOnly)",
    "(! galois.subsystem.WithSynchronousRocketTiles)",
    "(! galois.system.WithoutPLIC)",
]
